### ISSUE TITLE
problem about nvidia-docker

### ISSUE THREAD

**Issue by gsygsy96** [ctensmeyer/binarization_2017#1]
xxx@xxx:~$ sudo nvidia-docker run -v /home/xxx:/data tensmeyerc/icdar2017:binarization_gpu python binarize_plm.py /data/input_file.jpg /data/output_file.png 0
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "binarize_plm.py", line 257, in <module>
    main(in_image, out_image)
  File "binarize_plm.py", line 191, in main
    rd_im = relative_darkness(image)
  File "binarize_plm.py", line 35, in relative_darkness
    if im.ndim == 3:
AttributeError: 'NoneType' object has no attribute 'ndim'
Loading Image
Computing RD features

Do you know how to fix it?

**Comment by ctensmeyer** [comment]
The issue here is that the code cannot find the input image.  When `cv2.imread()` loads an image from a non-existent file, it returns None rather than throwing an exception.  

Are you sure that the path `/home/xxx/input_file.jpg` exists on your system and is a valid image file?
